#!/bin/sh
#
# Nagios AJP plugin.
#

JAVA_CMD=`which java`

if [ -z $JAVA_CMD ]
then

  if [ -x $JAVA_HOME/bin/java ]
  then
    JAVA_CMD=$JAVA_HOME/bin/java
  else
    echo AJP CRITICAL - java not found.
    exit 2
  fi

fi

DIR=`dirname $0`
$JAVA_CMD -classpath "$DIR/check_ajp_libs/*" org.dtornkaew.nagois.plugins.NagiosAjpClient "$@"

